# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
osx_image: xcode7.3
# cache: cocoapods
podfile: Example/Podfile
before_install:
 - gem install cocoapods # Since Travis is not always on latest version
 - pod install --project-directory=Example # Required in order to reference SGYKVOSafeNSObject during pod lib lint
 - pod repo update # Newly required by Cocoapods 1.0
script:
- set -o pipefail && xcodebuild test -workspace Example/SGYSwiftJSON.xcworkspace -scheme SGYSwiftJSON-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO -destination 'platform=iOS Simulator,name=iPhone 6,OS=9.1' | xcpretty
- pod lib lint
